# Generated by Django 4.2.17 on 2024-12-24 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
